// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnU6FsB4eHX_kqUYJ-YAxZIL6dYeWXDFw',
    appId: '1:621718528696:web:8b0c362231ab8efb164a4d',
    messagingSenderId: '621718528696',
    projectId: 'money-manager-c0156',
    authDomain: 'money-manager-c0156.firebaseapp.com',
    databaseURL: 'https://money-manager-c0156-default-rtdb.firebaseio.com',
    storageBucket: 'money-manager-c0156.appspot.com',
    measurementId: 'G-VF3177D0PZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoXlsRM9_au7R3W74Li7l6AQCOcrJ2hzU',
    appId: '1:621718528696:android:6508dc5f47271697164a4d',
    messagingSenderId: '621718528696',
    projectId: 'money-manager-c0156',
    databaseURL: 'https://money-manager-c0156-default-rtdb.firebaseio.com',
    storageBucket: 'money-manager-c0156.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK6rg-nkkKSBJqR8XJiObRWs5P9g9cH3I',
    appId: '1:621718528696:ios:52a39f5457a26bd2164a4d',
    messagingSenderId: '621718528696',
    projectId: 'money-manager-c0156',
    databaseURL: 'https://money-manager-c0156-default-rtdb.firebaseio.com',
    storageBucket: 'money-manager-c0156.appspot.com',
    androidClientId: '621718528696-9b9n9hk47u7aknl6au3tqamsq39eme91.apps.googleusercontent.com',
    iosClientId: '621718528696-o94hrrt6ja76v48i5b6p4d8g440na5fc.apps.googleusercontent.com',
    iosBundleId: 'com.example.lab18',
  );
}
